### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by liamzebedee** [tinychainorg/tinychain#1]
## "TerryDavis" Testnet

 - [x] cryptography
   - [x] generate keypair
   - [x] sign
   - [x] verify sig
 - [x] state machine & VM
   - [x] brainfuck VM
   - [x] add gas metering
   - [x] dump memory
   - [x] state machine - accounts, apply/evaluate calls
   - [x] gas market
 - [x] transactions
   - [x] hash
   - [x] signature
 - [x] protocol / RPC
   - [x] HTTP RPC
   - [x] protocol
 - [x] barebones bitcoin consensus
   - [x] mining / hashcash
   - [x] difficulty retargeting
   - [x] computing accumulated difficulty
   - [x] computing heaviest chain (tip)
 - [x] networked bitcoin consensus
   - [x] modify protocol_http to broadcast blocks, retrieve blocks
   - [x] run e2e test with two nodes mining in separate places
   - [x] nodes broadcast blocks
   - [x] nodes sync tips
   - [x] nodes reorg correctly
   - [x] difficulty readjustment is correct
   - [ ] test consensus is achieved
 - [ ] build out fully working brainfuck blockchain
   - [ ] connect consensus engine to tx sequencing
   - [ ] rerun the state machine on new consensus tip
   - [ ] build out a dumb demo - 
     - [ ] web app
     - [ ] run brainfuck code - RPC to dump memory, send txs
     - [ ] somehow add a transfer tx??

## Testnet 2

 - [ ] max block size - DoS attacks
 - [ ] max tx gas 
 - [ ] ZK coin - mine, generate proof of inserting root into merkle thing, don't reveal which. now
